name: hledger # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.34' # just for humans, typically '1.2+git' or '1.3.2'
summary: Robust, intuitive plain text accounting # 79 char long summary
description: |
  hledger is lightweight, cross platform, multi-currency, double-entry accounting software. 
  It lets you track money, investments, cryptocurrencies, invoices, time, inventory and more, 
  in a safe, future-proof plain text data format with full version control and privacy.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hledger:
    command: bin/hledger
  ui: # hledger.ui
    command: bin/hledger-ui
  web: # hledger.web
    command: bin/hledger-web

parts:
  # my-part:
  #   plugin: nil # 플러그인 없음
  hledger:
    # See 'snapcraft plugins'
    plugin: nil # 플러그인 없음
    source: https://github.com/simonmichael/hledger # hledger git 저장소에서 소스 가져오기
    source-tag: "1.34" # 빌드할 Git Tag 지정
    source-type: git # 소스 유형 지정
    build-environment:
    - PATH: "/root/.local/bin:$PATH" # PATH 설정
    build-packages: # 빌드할 떄 필요한 의존성
    - libgmp-dev
    - libtinfo-dev
    - zlib1g-dev
    - curl # Stack 설치 시 curl 필요하므로 추가
    override-build: | # build 시나리오 재정의
      craftctl default
      curl -sSL https://get.haskellstack.org/ | sh
      stack update
      stack build
      stack install --local-bin-path $CRAFT_PART_INSTALL/bin/